### ISSUE TITLE
Reviewing R7RS bugs

### ISSUE THREAD

**Issue by jmhufflen** [lexi-lambda/racket-r7rs#4]
- Defining a library can be done as follows:

(define-library (something)
  (export ...) (import ...)
  (define another-thing ...)
  (define year-another ...)
  ...)

although R7RS makes precise that definitions must be grouped under "begin":

(define-library (something)
  (export ...) (import ...)
  (begin
    (define another-thing ...)
    (define year-another ...)
    ...))
- This point is already present for "#lang racket" and complicates debugging of bytevectors. In R7RS, such data are self-evaluating:
# u8(48) ==> #u8(48)

whereas Racket implementation tries to display corresponding characters as far as possible:
# u8(48) ==> #"0"

from my point of view, we already have the function "utf8->string" for such use.
- The function "features" results :

(r7rs racket exact-closed exact-complex ieee-float full-unicode ratios)

these informations are ok, but should be include items about operating system and encoding for 16-bit words (little/big-endian). Such information could be successfully used by the "cond-expand" form.

The rest is OK, as far as I know. Moreover, I tried this implementation with great pleasure.

J.-M. Hufflen

**Comment by lexi-lambda** [comment]
I have split the first two points into issues #5 and #6. For the last point, however, I don’t think that feature is implementable because Racket bytecode is platform-agnostic. Since `cond-expand` runs at compile-time, it would be possible to, for example, compile a program on a Linux machine and subsequently run that same program on Windows. Therefore, I believe such a capability would be unreliable (the check must be performed at _runtime_ instead).

It would theoretically be possible to write an implementation of `cond-expand` that interprets certain feature identifiers specially and defers the check to runtime, but this seems like it would go against the spirit of the definition of `cond-expand`, which the standard explicitly states is used to **_statically**_ _expand different expressions_, which implies completely compile-time execution.

Thanks again for the reports!
